Repository AIRBNB-2M/Backend, pull requests merged in 2025-08, with the labels that each got.

#17 Feature/auth model
  src/main/java/project/airbnb/clone/config/auth/SecurityConfig.java
  src/main/java/project/airbnb/clone/consts/SocialType.java
  src/main/java/project/airbnb/clone/model/Attributes.java
  src/main/java/project/airbnb/clone/model/FormUser.java
  src/main/java/project/airbnb/clone/model/GoogleUser.java
  src/main/java/project/airbnb/clone/model/KakaoOidcUser.java
  src/main/java/project/airbnb/clone/model/KakaoUser.java
  src/main/java/project/airbnb/clone/model/NaverUser.java
  src/main/java/project/airbnb/clone/model/OAuth2ProviderUser.java
  src/main/java/project/airbnb/clone/model/OAuthUtils.java
  src/main/java/project/airbnb/clone/model/PrincipalUser.java
  src/main/java/project/airbnb/clone/model/ProviderUser.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 기능 추가, 완료, 환경 설정

#18 :sparkles: OAuth 인증 기본 베이스 코드 및 구글 인증 로직
  src/main/java/project/airbnb/clone/common/converters/ProviderUserConverter.java
  src/main/java/project/airbnb/clone/common/converters/ProviderUserRequest.java
  src/main/java/project/airbnb/clone/common/converters/impls/DelegatingProviderUserConverter.java
  src/main/java/project/airbnb/clone/common/converters/impls/OAuth2GoogleProviderUserConverter.java
  src/main/java/project/airbnb/clone/common/handlers/success/JwtAuthenticationSuccessHandler.java
  src/main/java/project/airbnb/clone/config/BeanConfig.java
  src/main/java/project/airbnb/clone/config/auth/SecurityConfig.java
  src/main/java/project/airbnb/clone/consts/SocialType.java
  src/main/java/project/airbnb/clone/entity/Guest.java
  src/main/java/project/airbnb/clone/model/social/GoogleUser.java
  src/main/java/project/airbnb/clone/model/social/KakaoOidcUser.java
  src/main/java/project/airbnb/clone/model/social/KakaoUser.java
  src/main/java/project/airbnb/clone/model/social/NaverUser.java
  src/main/java/project/airbnb/clone/repository/guest/GuestRepository.java
  src/main/java/project/airbnb/clone/service/guest/GuestService.java
  src/main/java/project/airbnb/clone/service/security/AbstractOAuth2UserService.java
  src/main/java/project/airbnb/clone/service/security/CustomOAuth2UserService.java
  src/main/java/project/airbnb/clone/service/security/CustomOidcUserService.java
  src/main/java/project/airbnb/clone/service/security/CustomUserDetailsService.java
Labels: 기능 추가, 완료

#20 Feature/oauth naver
  src/main/java/project/airbnb/clone/common/converters/impls/DelegatingProviderUserConverter.java
  src/main/java/project/airbnb/clone/common/converters/impls/OAuth2NaverProviderUserConverter.java
  src/main/java/project/airbnb/clone/model/FormUser.java
  src/main/java/project/airbnb/clone/model/OAuth2ProviderUser.java
  src/main/java/project/airbnb/clone/model/ProviderUser.java
  src/main/java/project/airbnb/clone/model/social/GoogleUser.java
  src/main/java/project/airbnb/clone/model/social/KakaoOidcUser.java
  src/main/java/project/airbnb/clone/model/social/KakaoUser.java
  src/main/java/project/airbnb/clone/model/social/NaverUser.java
  src/main/java/project/airbnb/clone/service/guest/GuestService.java
  src/main/resources/application.yml
Labels: 기능 추가, 완료

#23 refactor: RestTemplate를 RestClient로 변경
  src/main/java/project/airbnb/clone/config/RestClientConfig.java
  src/main/java/project/airbnb/clone/config/RestTemplateConfig.java
  src/main/java/project/airbnb/clone/service/TourApiService.java
Labels: 리팩토링, 완료

#24 :sparkles: 깃허브 인증 로직
  src/main/java/project/airbnb/clone/common/converters/GitHubAppClient.java
  src/main/java/project/airbnb/clone/common/converters/impls/DelegatingProviderUserConverter.java
  src/main/java/project/airbnb/clone/common/converters/impls/OAuth2GithubProviderUserConverter.java
  src/main/java/project/airbnb/clone/config/http/HttpClientConfig.java
  src/main/java/project/airbnb/clone/model/social/GithubUser.java
  src/main/java/project/airbnb/clone/service/security/CustomOAuth2UserService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 기능 추가, 완료

#28 Test/controller
  build.gradle
  src/docs/asciidoc/guest-signup.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/project/airbnb/clone/CloneApplication.java
  src/main/java/project/airbnb/clone/config/JpaConfig.java
  src/main/java/project/airbnb/clone/controller/guests/GuestController.java
  src/main/java/project/airbnb/clone/dto/guest/SignupRequestDto.java
  src/test/java/project/airbnb/clone/config/RestDocsConfig.java
  src/test/java/project/airbnb/clone/controller/ControllerTestSupport.java
  src/test/java/project/airbnb/clone/controller/RestDocsTestSupport.java
  src/test/java/project/airbnb/clone/controller/guests/GuestControllerTest.java
  src/test/resources/application.yml
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: 완료, 테스트, 환경 설정

#34 Feature/access token
  build.gradle
  src/main/java/project/airbnb/clone/common/jwt/JwtProvider.java
  src/main/java/project/airbnb/clone/config/RedisConfig.java
  src/main/java/project/airbnb/clone/config/advice/ExceptionControllerAdvice.java
  src/main/java/project/airbnb/clone/config/security/configs/SecurityConfig.java
  src/main/java/project/airbnb/clone/config/security/handlers/failer/CustomAuthenticationEntryPoint.java
  src/main/java/project/airbnb/clone/config/security/jwt/JwtExceptionFilter.java
  src/main/java/project/airbnb/clone/controller/auth/RefreshTokenController.java
  src/main/java/project/airbnb/clone/repository/redis/RedisRepository.java
  src/main/java/project/airbnb/clone/service/jwt/TokenService.java
  src/main/resources/application-local.yml
Labels: 기능 추가, 완료, 환경 설정

#36 Feature/logout
  src/main/java/project/airbnb/clone/common/advice/ErrorResponse.java
  src/main/java/project/airbnb/clone/common/advice/ExceptionControllerAdvice.java
  src/main/java/project/airbnb/clone/common/clients/GitHubAppClient.java
  src/main/java/project/airbnb/clone/common/clients/KakaoAppClient.java
  src/main/java/project/airbnb/clone/common/clients/NaverAppClient.java
  src/main/java/project/airbnb/clone/common/converters/GitHubAppClient.java
  src/main/java/project/airbnb/clone/common/events/logout/OAuthLogoutEvent.java
  src/main/java/project/airbnb/clone/common/events/logout/OAuthLogoutListener.java
  src/main/java/project/airbnb/clone/common/jwt/JwtProperties.java
  src/main/java/project/airbnb/clone/common/jwt/JwtProvider.java
  src/main/java/project/airbnb/clone/config/http/HttpClientConfig.java
  src/main/java/project/airbnb/clone/config/infra/HttpClientConfig.java
  src/main/java/project/airbnb/clone/config/infra/RedisConfig.java
  src/main/java/project/airbnb/clone/config/infra/RestClientConfig.java
  src/main/java/project/airbnb/clone/config/jpa/JpaConfig.java
  src/main/java/project/airbnb/clone/config/security/configs/PasswordEncoderConfig.java
  src/main/java/project/airbnb/clone/config/security/handlers/failer/RestAuthenticationFailureHandler.java
  src/main/java/project/airbnb/clone/config/security/handlers/success/OAuthAuthenticationSuccessHandler.java
  src/main/java/project/airbnb/clone/config/security/handlers/success/RestAuthenticationSuccessHandler.java
  src/main/java/project/airbnb/clone/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/project/airbnb/clone/config/security/jwt/JwtExceptionFilter.java
  src/main/java/project/airbnb/clone/controller/auth/RefreshTokenController.java
  src/main/java/project/airbnb/clone/model/AuthProviderUser.java
  src/main/java/project/airbnb/clone/model/PrincipalUser.java
  src/main/java/project/airbnb/clone/model/ProviderUser.java
  src/main/java/project/airbnb/clone/model/social/GithubUser.java
  src/main/java/project/airbnb/clone/model/social/GoogleUser.java
  src/main/java/project/airbnb/clone/model/social/KakaoOidcUser.java
  src/main/java/project/airbnb/clone/model/social/KakaoUser.java
  src/main/java/project/airbnb/clone/model/social/NaverUser.java
  src/main/java/project/airbnb/clone/service/jwt/TokenService.java
  src/main/java/project/airbnb/clone/service/security/CustomOAuth2UserService.java
Labels: 기능 추가, 리팩토링, 완료

#41 Test/fetch accommodations
  build.gradle
  src/main/java/project/airbnb/clone/AppRun.java
  src/main/java/project/airbnb/clone/common/batch/AccommodationBatchConfig.java
  src/main/java/project/airbnb/clone/common/batch/AccommodationWriter.java
  src/main/java/project/airbnb/clone/common/batch/AreaBasedSyncListReader.java
  src/main/java/project/airbnb/clone/common/batch/DetailCommonProcessor.java
  src/main/java/project/airbnb/clone/common/batch/DetailInfoProcessor.java
  src/main/java/project/airbnb/clone/common/batch/DetailIntroProcessor.java
  src/main/java/project/airbnb/clone/common/batch/JobScheduler.java
  src/main/java/project/airbnb/clone/common/clients/TourApiClient.java
  src/main/java/project/airbnb/clone/config/infra/HttpClientConfig.java
  src/main/java/project/airbnb/clone/controller/auth/TestController.java
  src/main/java/project/airbnb/clone/dto/AccommodationProcessorDto.java
  src/main/java/project/airbnb/clone/dto/TourApiResponse.java
  src/main/java/project/airbnb/clone/entity/Accommodation.java
  src/main/java/project/airbnb/clone/entity/AccommodationImage.java
  src/main/java/project/airbnb/clone/entity/Amenity.java
  src/main/java/project/airbnb/clone/entity/AreaCode.java
  src/main/java/project/airbnb/clone/entity/SigunguCode.java
  src/main/java/project/airbnb/clone/repository/AccommodationRepository.java
  src/main/java/project/airbnb/clone/repository/AreaCodeRepository.java
  src/main/java/project/airbnb/clone/repository/SigunguCodeRepository.java
  src/main/java/project/airbnb/clone/service/TourAmenityService.java
  src/main/java/project/airbnb/clone/service/TourApiService.java
  src/main/java/project/airbnb/clone/service/TourImageService.java
  src/main/resources/application.yml
Labels: 기능 추가, 진행 중, 환경 설정
